
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATE LP NAME NDY NEWLINE PLUS POINT RP UND UNK\n    Family : Couples \n\n    \n    Couples : Couples Couple \n            | Couple \n    \n    Couple : Person PLUS Person NEWLINE Children NEWLINE\n    \n    Couple : Person error Person NEWLINE Children NEWLINE\n    \n    Couple : Person PLUS Person error Children NEWLINE\n    \n    Person : Names Nickname Dates\n           | Names Dates\n           | UND\n    \n    Names : Names NAME\n          | NAME\n          | empty\n    \n    Dates : LP DATE DATE RP   \n          | LP DATE NDY RP    \n          | LP DATE UNK RP   \n          | LP UNK NDY RP   \n          | LP UNK DATE RP   \n          | UNK\n    \n    Children : Children Child\n             | Child\n             | empty\n\n             \n    \n    Child : POINT Person NEWLINE\n    \n    Nickname : LP Names RP\n    \n    empty :\n    '
    
_lr_action_items = {'UND':([0,2,3,9,10,11,36,44,47,48,],[6,6,-3,-2,6,6,6,-4,-6,-5,]),'NAME':([0,2,3,5,7,8,9,10,11,14,15,21,36,44,47,48,],[7,7,-3,14,-11,-12,-2,7,7,-10,7,14,7,-4,-6,-5,]),'LP':([0,2,3,5,7,8,9,10,11,12,14,27,36,44,47,48,],[-24,-24,-3,15,-11,-12,-2,-24,-24,20,-10,-23,-24,-4,-6,-5,]),'UNK':([0,2,3,5,7,8,9,10,11,12,14,15,20,22,27,36,44,47,48,],[-24,-24,-3,16,-11,-12,-2,-24,-24,16,-10,23,23,30,-23,-24,-4,-6,-5,]),'$end':([1,2,3,9,44,47,48,],[0,-1,-3,-2,-4,-6,-5,]),'PLUS':([4,6,13,16,19,39,40,41,42,43,],[10,-9,-8,-18,-7,-13,-14,-15,-16,-17,]),'error':([4,6,13,16,17,19,39,40,41,42,43,],[11,-9,-8,-18,25,-7,-13,-14,-15,-16,-17,]),'NEWLINE':([6,13,16,17,18,19,24,25,26,33,34,35,37,38,39,40,41,42,43,45,46,49,],[-9,-8,-18,24,26,-7,-24,-24,-24,44,-20,-21,47,48,-13,-14,-15,-16,-17,-19,49,-22,]),'RP':([7,8,14,15,21,28,29,30,31,32,],[-11,-12,-10,-24,27,39,40,41,42,43,]),'DATE':([15,20,22,23,],[22,22,28,32,]),'NDY':([22,23,],[29,31,]),'POINT':([24,25,26,33,34,35,37,38,45,49,],[36,36,36,36,-20,-21,36,36,-19,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Family':([0,],[1,]),'Couples':([0,],[2,]),'Couple':([0,2,],[3,9,]),'Person':([0,2,10,11,36,],[4,4,17,18,46,]),'Names':([0,2,10,11,15,36,],[5,5,5,5,21,5,]),'empty':([0,2,10,11,15,24,25,26,36,],[8,8,8,8,8,35,35,35,8,]),'Nickname':([5,],[12,]),'Dates':([5,12,],[13,19,]),'Children':([24,25,26,],[33,37,38,]),'Child':([24,25,26,33,37,38,],[34,34,34,45,45,45,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Family","S'",1,None,None,None),
  ('Family -> Couples','Family',1,'p_family','gramma.py',43),
  ('Couples -> Couples Couple','Couples',2,'p_couples','gramma.py',52),
  ('Couples -> Couple','Couples',1,'p_couples','gramma.py',53),
  ('Couple -> Person PLUS Person NEWLINE Children NEWLINE','Couple',6,'p_couple','gramma.py',68),
  ('Couple -> Person error Person NEWLINE Children NEWLINE','Couple',6,'p_couple_error_plus','gramma.py',75),
  ('Couple -> Person PLUS Person error Children NEWLINE','Couple',6,'p_couple_error_newline_2','gramma.py',82),
  ('Person -> Names Nickname Dates','Person',3,'p_person','gramma.py',89),
  ('Person -> Names Dates','Person',2,'p_person','gramma.py',90),
  ('Person -> UND','Person',1,'p_person','gramma.py',91),
  ('Names -> Names NAME','Names',2,'p_names','gramma.py',135),
  ('Names -> NAME','Names',1,'p_names','gramma.py',136),
  ('Names -> empty','Names',1,'p_names','gramma.py',137),
  ('Dates -> LP DATE DATE RP','Dates',4,'p_dates','gramma.py',149),
  ('Dates -> LP DATE NDY RP','Dates',4,'p_dates','gramma.py',150),
  ('Dates -> LP DATE UNK RP','Dates',4,'p_dates','gramma.py',151),
  ('Dates -> LP UNK NDY RP','Dates',4,'p_dates','gramma.py',152),
  ('Dates -> LP UNK DATE RP','Dates',4,'p_dates','gramma.py',153),
  ('Dates -> UNK','Dates',1,'p_dates','gramma.py',154),
  ('Children -> Children Child','Children',2,'p_children','gramma.py',175),
  ('Children -> Child','Children',1,'p_children','gramma.py',176),
  ('Children -> empty','Children',1,'p_children','gramma.py',177),
  ('Child -> POINT Person NEWLINE','Child',3,'p_child','gramma.py',195),
  ('Nickname -> LP Names RP','Nickname',3,'p_nickname','gramma.py',203),
  ('empty -> <empty>','empty',0,'p_empty','gramma.py',212),
]
