
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DATE LP NAME NDY NEWLINE PLUS POINT RP UND UNK\n    Family : Couples \n\n    \n    Names : Names NAME\n          | NAME\n          | empty\n    \n    Couples : Couples Couple \n            | Couple \n    \n    Couple : Person PLUS Person NEWLINE Children NEWLINE\n    \n    Person : Names Dates\n           | UND\n    \n    Dates : LP DATE DATE RP   \n          | LP DATE NDY RP    \n          | LP DATE UNK RP   \n          | LP UNK NDY RP   \n          | LP UNK DATE RP   \n          | UNK\n    \n    Children : Children Child\n             | Child\n             | empty\n\n             \n    \n    Child : POINT Person NEWLINE\n    \n    empty :\n    '
    
_lr_action_items = {'UND':([0,2,3,9,10,27,33,],[6,6,-6,-5,6,6,-7,]),'NAME':([0,2,3,5,7,8,9,10,12,27,33,],[7,7,-6,12,-3,-4,-5,7,-2,7,-7,]),'LP':([0,2,3,5,7,8,9,10,12,27,33,],[-20,-20,-6,13,-3,-4,-5,-20,-2,-20,-7,]),'UNK':([0,2,3,5,7,8,9,10,12,13,16,27,33,],[-20,-20,-6,14,-3,-4,-5,-20,-2,17,21,-20,-7,]),'$end':([1,2,3,9,33,],[0,-1,-6,-5,-7,]),'PLUS':([4,6,11,14,28,29,30,31,32,],[10,-9,-8,-15,-10,-11,-12,-13,-14,]),'NEWLINE':([6,11,14,15,18,24,25,26,28,29,30,31,32,34,35,36,],[-9,-8,-15,18,-20,33,-17,-18,-10,-11,-12,-13,-14,-16,36,-19,]),'DATE':([13,16,17,],[16,19,23,]),'NDY':([16,17,],[20,22,]),'POINT':([18,24,25,26,34,36,],[27,27,-17,-18,-16,-19,]),'RP':([19,20,21,22,23,],[28,29,30,31,32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Family':([0,],[1,]),'Couples':([0,],[2,]),'Couple':([0,2,],[3,9,]),'Person':([0,2,10,27,],[4,4,15,35,]),'Names':([0,2,10,27,],[5,5,5,5,]),'empty':([0,2,10,18,27,],[8,8,8,26,8,]),'Dates':([5,],[11,]),'Children':([18,],[24,]),'Child':([18,24,],[25,34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Family","S'",1,None,None,None),
  ('Family -> Couples','Family',1,'p_family','gramma.py',44),
  ('Names -> Names NAME','Names',2,'p_names','gramma.py',52),
  ('Names -> NAME','Names',1,'p_names','gramma.py',53),
  ('Names -> empty','Names',1,'p_names','gramma.py',54),
  ('Couples -> Couples Couple','Couples',2,'p_couples','gramma.py',65),
  ('Couples -> Couple','Couples',1,'p_couples','gramma.py',66),
  ('Couple -> Person PLUS Person NEWLINE Children NEWLINE','Couple',6,'p_couple','gramma.py',81),
  ('Person -> Names Dates','Person',2,'p_person','gramma.py',96),
  ('Person -> UND','Person',1,'p_person','gramma.py',97),
  ('Dates -> LP DATE DATE RP','Dates',4,'p_dates','gramma.py',131),
  ('Dates -> LP DATE NDY RP','Dates',4,'p_dates','gramma.py',132),
  ('Dates -> LP DATE UNK RP','Dates',4,'p_dates','gramma.py',133),
  ('Dates -> LP UNK NDY RP','Dates',4,'p_dates','gramma.py',134),
  ('Dates -> LP UNK DATE RP','Dates',4,'p_dates','gramma.py',135),
  ('Dates -> UNK','Dates',1,'p_dates','gramma.py',136),
  ('Children -> Children Child','Children',2,'p_children','gramma.py',157),
  ('Children -> Child','Children',1,'p_children','gramma.py',158),
  ('Children -> empty','Children',1,'p_children','gramma.py',159),
  ('Child -> POINT Person NEWLINE','Child',3,'p_child','gramma.py',177),
  ('empty -> <empty>','empty',0,'p_empty','gramma.py',198),
]
