
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID IGNORED PF PP PYTHON VIRFSGram : Prods PYTHON IGNOREDProds : Prod ProdsProds : ProdProd : ID PP IDS PFIDS : IDS VIR IDIDS : ID'
    
_lr_action_items = {'ID':([0,3,7,11,12,],[4,4,9,-4,13,]),'$end':([1,8,],[0,-1,]),'PYTHON':([2,3,6,11,],[5,-3,-2,-4,]),'PP':([4,],[7,]),'IGNORED':([5,],[8,]),'PF':([9,10,13,],[-6,11,-5,]),'VIR':([9,10,13,],[-6,12,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'FSGram':([0,],[1,]),'Prods':([0,3,],[2,6,]),'Prod':([0,3,],[3,3,]),'IDS':([7,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FSGram","S'",1,None,None,None),
  ('FSGram -> Prods PYTHON IGNORED','FSGram',3,'p_FSGram','ANBcompiler_yacc.py',10),
  ('Prods -> Prod Prods','Prods',2,'p_Prods','ANBcompiler_yacc.py',15),
  ('Prods -> Prod','Prods',1,'p_Prodsingle','ANBcompiler_yacc.py',19),
  ('Prod -> ID PP IDS PF','Prod',4,'p_Prod','ANBcompiler_yacc.py',23),
  ('IDS -> IDS VIR ID','IDS',3,'p_IDS','ANBcompiler_yacc.py',26),
  ('IDS -> ID','IDS',1,'p_IDSingle','ANBcompiler_yacc.py',30),
]
